// Copyright 2010 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"runtime"
)

func main() {
	runtime.GOMAXPROCS(2)
	t := New(true, true)

	/*package main
	  type Peg Peg {
	   *Tree
	  }*/
	t.AddPackage("main")
	t.AddPeg("Peg")
	t.AddState(`
 *Tree
`)

	/* Grammar         <- Spacing 'package' Spacing Identifier      { p.AddPackage(buffer[begin:end]) }
	   'type' Spacing Identifier         { p.AddPeg(buffer[begin:end]) }
	   'Peg' Spacing Action              { p.AddState(buffer[begin:end]) }
	   commit
	   Definition+ EndOfFile */
	t.AddRule("Grammar")
	t.AddName("Spacing")
	t.AddCharacter(`p`)
	t.AddCharacter(`a`)
	t.AddSequence()
	t.AddCharacter(`c`)
	t.AddSequence()
	t.AddCharacter(`k`)
	t.AddSequence()
	t.AddCharacter(`a`)
	t.AddSequence()
	t.AddCharacter(`g`)
	t.AddSequence()
	t.AddCharacter(`e`)
	t.AddSequence()
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddName("Identifier")
	t.AddSequence()
	t.AddAction(" p.AddPackage(buffer[begin:end]) ")
	t.AddSequence()
	t.AddCharacter(`t`)
	t.AddCharacter(`y`)
	t.AddSequence()
	t.AddCharacter(`p`)
	t.AddSequence()
	t.AddCharacter(`e`)
	t.AddSequence()
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddName("Identifier")
	t.AddSequence()
	t.AddAction(" p.AddPeg(buffer[begin:end]) ")
	t.AddSequence()
	t.AddCharacter(`P`)
	t.AddCharacter(`e`)
	t.AddSequence()
	t.AddCharacter(`g`)
	t.AddSequence()
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddName("Action")
	t.AddSequence()
	t.AddAction(" p.AddState(buffer[begin:end]) ")
	t.AddSequence()
	t.AddCommit()
	t.AddSequence()
	t.AddName("Definition")
	t.AddPlus()
	t.AddSequence()
	t.AddName("EndOfFile")
	t.AddSequence()
	t.AddExpression()

	/* Definition      <- Identifier                   { p.AddRule(buffer[begin:end]) }
	   LEFTARROW Expression         { p.AddExpression() } &(Identifier LEFTARROW / !.) commit */
	t.AddRule("Definition")
	t.AddName("Identifier")
	t.AddAction(" p.AddRule(buffer[begin:end]) ")
	t.AddSequence()
	t.AddName("LEFTARROW")
	t.AddSequence()
	t.AddName("Expression")
	t.AddSequence()
	t.AddAction(" p.AddExpression() ")
	t.AddSequence()
	t.AddName("Identifier")
	t.AddName("LEFTARROW")
	t.AddSequence()
	t.AddDot()
	t.AddPeekNot()
	t.AddAlternate()
	t.AddPeekFor()
	t.AddSequence()
	t.AddCommit()
	t.AddSequence()
	t.AddExpression()

	/* Expression      <- Sequence (SLASH Sequence     { p.AddAlternate() }
	           )* (SLASH           { p.AddNil(); p.AddAlternate() }
	              )?
	/ { p.AddNil() } */
	t.AddRule("Expression")
	t.AddName("Sequence")
	t.AddName("SLASH")
	t.AddName("Sequence")
	t.AddSequence()
	t.AddAction(" p.AddAlternate() ")
	t.AddSequence()
	t.AddStar()
	t.AddSequence()
	t.AddName("SLASH")
	t.AddAction(" p.AddNil(); p.AddAlternate() ")
	t.AddSequence()
	t.AddQuery()
	t.AddSequence()
	t.AddAction(" p.AddNil() ")
	t.AddAlternate()
	t.AddExpression()

	/* Sequence        <- Prefix (Prefix               { p.AddSequence() }
	   )* */
	t.AddRule("Sequence")
	t.AddName("Prefix")
	t.AddName("Prefix")
	t.AddAction(" p.AddSequence() ")
	t.AddSequence()
	t.AddStar()
	t.AddSequence()
	t.AddExpression()

	/* Prefix          <- AND Action                   { p.AddPredicate(buffer[begin:end]) }
	   / AND Suffix                   { p.AddPeekFor() }
	   / NOT Suffix                   { p.AddPeekNot() }
	   /     Suffix */
	t.AddRule("Prefix")
	t.AddName("AND")
	t.AddName("Action")
	t.AddSequence()
	t.AddAction(" p.AddPredicate(buffer[begin:end]) ")
	t.AddSequence()
	t.AddName("AND")
	t.AddName("Suffix")
	t.AddSequence()
	t.AddAction(" p.AddPeekFor() ")
	t.AddSequence()
	t.AddAlternate()
	t.AddName("NOT")
	t.AddName("Suffix")
	t.AddSequence()
	t.AddAction(" p.AddPeekNot() ")
	t.AddSequence()
	t.AddAlternate()
	t.AddName("Suffix")
	t.AddAlternate()
	t.AddExpression()

	/* Suffix          <- Primary (QUESTION            { p.AddQuery() }
	   / STAR             { p.AddStar() }
	   / PLUS             { p.AddPlus() }
	 )? */
	t.AddRule("Suffix")
	t.AddName("Primary")
	t.AddName("QUESTION")
	t.AddAction(" p.AddQuery() ")
	t.AddSequence()
	t.AddName("STAR")
	t.AddAction(" p.AddStar() ")
	t.AddSequence()
	t.AddAlternate()
	t.AddName("PLUS")
	t.AddAction(" p.AddPlus() ")
	t.AddSequence()
	t.AddAlternate()
	t.AddQuery()
	t.AddSequence()
	t.AddExpression()

	/* Primary         <- 'commit' Spacing             { p.AddCommit() }
	   / Identifier !LEFTARROW        { p.AddName(buffer[begin:end]) }
	   / OPEN Expression CLOSE
	   / Literal
	   / Class
	   / DOT                          { p.AddDot() }
	   / Action                       { p.AddAction(buffer[begin:end]) }
	   / BEGIN                        { p.AddBegin() }
	   / END                          { p.AddEnd() } */
	t.AddRule("Primary")
	t.AddCharacter(`c`)
	t.AddCharacter(`o`)
	t.AddSequence()
	t.AddCharacter(`m`)
	t.AddSequence()
	t.AddCharacter(`m`)
	t.AddSequence()
	t.AddCharacter(`i`)
	t.AddSequence()
	t.AddCharacter(`t`)
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddAction(" p.AddCommit() ")
	t.AddSequence()
	t.AddName("Identifier")
	t.AddName("LEFTARROW")
	t.AddPeekNot()
	t.AddSequence()
	t.AddAction(" p.AddName(buffer[begin:end]) ")
	t.AddSequence()
	t.AddAlternate()
	t.AddName("OPEN")
	t.AddName("Expression")
	t.AddSequence()
	t.AddName("CLOSE")
	t.AddSequence()
	t.AddAlternate()
	t.AddName("Literal")
	t.AddAlternate()
	t.AddName("Class")
	t.AddAlternate()
	t.AddName("DOT")
	t.AddAction(" p.AddDot() ")
	t.AddSequence()
	t.AddAlternate()
	t.AddName("Action")
	t.AddAction(" p.AddAction(buffer[begin:end]) ")
	t.AddSequence()
	t.AddAlternate()
	t.AddName("BEGIN")
	t.AddAction(" p.AddBegin() ")
	t.AddSequence()
	t.AddAlternate()
	t.AddName("END")
	t.AddAction(" p.AddEnd() ")
	t.AddSequence()
	t.AddAlternate()
	t.AddExpression()

	/* Identifier      <- < IdentStart IdentCont* > Spacing */
	t.AddRule("Identifier")
	t.AddBegin()
	t.AddName("IdentStart")
	t.AddSequence()
	t.AddName("IdentCont")
	t.AddStar()
	t.AddSequence()
	t.AddEnd()
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* IdentStart      <- [a-zA-Z_] */
	t.AddRule("IdentStart")
	t.AddCharacter(`a`)
	t.AddCharacter(`z`)
	t.AddRange()
	t.AddCharacter(`A`)
	t.AddCharacter(`Z`)
	t.AddRange()
	t.AddAlternate()
	t.AddCharacter(`_`)
	t.AddAlternate()
	t.AddExpression()

	/* IdentCont       <- IdentStart / [0-9] */
	t.AddRule("IdentCont")
	t.AddName("IdentStart")
	t.AddCharacter(`0`)
	t.AddCharacter(`9`)
	t.AddRange()
	t.AddAlternate()
	t.AddExpression()

	/* Literal         <- ['] < (!['] Char )* > ['] Spacing
	   / ["] < (!["] Char )* > ["] Spacing */
	/*t.AddRule("Literal")
	t.AddClass("'")
	t.AddBegin()
	t.AddSequence()
	t.AddClass("'")
	t.AddPeekNot()
	t.AddName("Char")
	t.AddSequence()
	t.AddStar()
	t.AddSequence()
	t.AddEnd()
	t.AddSequence()
	t.AddClass("'")
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddClass(`"`)
	t.AddBegin()
	t.AddSequence()
	t.AddClass(`"`)
	t.AddPeekNot()
	t.AddName("Char")
	t.AddSequence()
	t.AddStar()
	t.AddSequence()
	t.AddEnd()
	t.AddSequence()
	t.AddClass(`"`)
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddAlternate()
	t.AddExpression()*/

	/* Literal         <- ['] (!['] Char)? (!['] Char          { p.AddSequence() }
	                      )* ['] Spacing
	   / ["] (!["] Char)? (!["] Char          { p.AddSequence() }
	                      )* ["] Spacing */
	t.AddRule("Literal")
	t.AddCharacter(`'`)
	t.AddCharacter(`'`)
	t.AddPeekNot()
	t.AddName("Char")
	t.AddSequence()
	t.AddQuery()
	t.AddSequence()
	t.AddCharacter(`'`)
	t.AddPeekNot()
	t.AddName("Char")
	t.AddSequence()
	t.AddAction(` p.AddSequence() `)
	t.AddSequence()
	t.AddStar()
	t.AddSequence()
	t.AddCharacter(`'`)
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddCharacter(`"`)
	t.AddCharacter(`"`)
	t.AddPeekNot()
	t.AddName("Char")
	t.AddSequence()
	t.AddQuery()
	t.AddSequence()
	t.AddCharacter(`"`)
	t.AddPeekNot()
	t.AddName("Char")
	t.AddSequence()
	t.AddAction(` p.AddSequence() `)
	t.AddSequence()
	t.AddStar()
	t.AddSequence()
	t.AddCharacter(`"`)
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddAlternate()
	t.AddExpression()

	/* Class           <- '[' < (!']' Range)* > ']' Spacing */
	/*t.AddRule("Class")
	t.AddString("[")
	t.AddBegin()
	t.AddSequence()
	t.AddString("]")
	t.AddPeekNot()
	t.AddName("Range")
	t.AddSequence()
	t.AddStar()
	t.AddSequence()
	t.AddEnd()
	t.AddSequence()
	t.AddString("]")
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()*/

	/* Class           <- '[' ( '^' Ranges                     { p.AddPeekNot(); p.AddDot(); p.AddSequence() }
	    / Ranges )?
	']' Spacing */
	t.AddRule("Class")
	t.AddCharacter(`[`)
	t.AddCharacter(`^`)
	t.AddName("Ranges")
	t.AddSequence()
	t.AddAction(` p.AddPeekNot(); p.AddDot(); p.AddSequence() `)
	t.AddSequence()
	t.AddName("Ranges")
	t.AddAlternate()
	t.AddQuery()
	t.AddSequence()
	t.AddCharacter(`]`)
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* Ranges          <- !']' Range (!']' Range  { p.AddAlternate() }
	   )* */
	t.AddRule("Ranges")
	t.AddCharacter(`]`)
	t.AddPeekNot()
	t.AddName("Range")
	t.AddSequence()
	t.AddCharacter(`]`)
	t.AddPeekNot()
	t.AddName("Range")
	t.AddSequence()
	t.AddAction(" p.AddAlternate() ")
	t.AddSequence()
	t.AddStar()
	t.AddSequence()
	t.AddExpression()

	/* Range           <- Char '-' Char / Char */
	/*t.AddRule("Range")
	t.AddName("Char")
	t.AddString("-")
	t.AddSequence()
	t.AddName("Char")
	t.AddSequence()
	t.AddName("Char")
	t.AddAlternate()
	t.AddExpression()*/

	/* Range           <- Char '-' Char { p.AddRange() }
	   / Char */
	t.AddRule("Range")
	t.AddName("Char")
	t.AddCharacter(`-`)
	t.AddSequence()
	t.AddName("Char")
	t.AddSequence()
	t.AddAction(" p.AddRange() ")
	t.AddSequence()
	t.AddName("Char")
	t.AddAlternate()
	t.AddExpression()

	/* Char            <- '\\' [abefnrtv'"\[\]\\]
	   / '\\' [0-3][0-7][0-7]
	   / '\\' [0-7][0-7]?
	   / '\\' '-'
	   / !'\\' . */
	/*t.AddRule("Char")
	t.AddString(`\\`)
	t.AddClass(`abefnrtv'"\[\]\\`)
	t.AddSequence()
	t.AddString(`\\`)
	t.AddClass("0-3")
	t.AddSequence()
	t.AddClass("0-7")
	t.AddSequence()
	t.AddClass("0-7")
	t.AddSequence()
	t.AddAlternate()
	t.AddString(`\\`)
	t.AddClass("0-7")
	t.AddSequence()
	t.AddClass("0-7")
	t.AddQuery()
	t.AddSequence()
	t.AddAlternate()
	t.AddString(`\\`)
	t.AddString("-")
	t.AddSequence()
	t.AddAlternate()
	t.AddString(`\\`)
	t.AddPeekNot()
	t.AddDot()
	t.AddSequence()
	t.AddAlternate()
	t.AddExpression()*/

	/* Char            <- '\\a'                      { p.AddCharacter("\a") }   # bell
	   / '\\b'                      { p.AddCharacter("\b") }   # bs
	   / '\\e'                      { p.AddCharacter("\x1B") } # esc
	   / '\\f'                      { p.AddCharacter("\f") }   # ff
	   / '\\n'                      { p.AddCharacter("\n") }   # nl
	   / '\\r'                      { p.AddCharacter("\r") }   # cr
	   / '\\t'                      { p.AddCharacter("\t") }   # ht
	   / '\\v'                      { p.AddCharacter("\v") }   # vt
	   / "\\'"                      { p.AddCharacter("'") }
	   / '\\"'                      { p.AddCharacter("\"") }
	   / '\\['                      { p.AddCharacter("[") }
	   / '\\]'                      { p.AddCharacter("]") }
	   / '\\-'                      { p.AddCharacter("-") }
	   / '\\' <[0-3][0-7][0-7]>     { p.AddOctalCharacter(buffer[begin:end]) }
	   / '\\' <[0-7][0-7]?>         { p.AddOctalCharacter(buffer[begin:end]) }
	   / '\\\\'                     { p.AddCharacter("\\") }
	   / !'\\' <.>                  { p.AddCharacter(buffer[begin:end]) } */
	t.AddRule("Char")
	t.AddCharacter("\\")
	t.AddCharacter(`a`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("\a") `)
	t.AddSequence()
	t.AddCharacter("\\")
	t.AddCharacter(`b`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("\b") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`e`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("\x1B") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`f`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("\f") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`n`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("\n") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`r`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("\r") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`t`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("\t") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`v`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("\v") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`'`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("'") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`"`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("\"") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`[`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("[") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`]`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("]") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter(`-`)
	t.AddSequence()
	t.AddAction(` p.AddCharacter("-") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddBegin()
	t.AddSequence()
	t.AddCharacter(`0`)
	t.AddCharacter(`3`)
	t.AddRange()
	t.AddSequence()
	t.AddCharacter(`0`)
	t.AddCharacter(`7`)
	t.AddRange()
	t.AddSequence()
	t.AddCharacter(`0`)
	t.AddCharacter(`7`)
	t.AddRange()
	t.AddSequence()
	t.AddEnd()
	t.AddSequence()
	t.AddAction(` p.AddOctalCharacter(buffer[begin:end]) `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddBegin()
	t.AddSequence()
	t.AddCharacter(`0`)
	t.AddCharacter(`7`)
	t.AddRange()
	t.AddSequence()
	t.AddCharacter(`0`)
	t.AddCharacter(`7`)
	t.AddRange()
	t.AddQuery()
	t.AddSequence()
	t.AddEnd()
	t.AddSequence()
	t.AddAction(` p.AddOctalCharacter(buffer[begin:end]) `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddCharacter("\\")
	t.AddSequence()
	t.AddAction(` p.AddCharacter("\\") `)
	t.AddSequence()
	t.AddAlternate()
	t.AddCharacter("\\")
	t.AddPeekNot()
	t.AddBegin()
	t.AddSequence()
	t.AddDot()
	t.AddSequence()
	t.AddEnd()
	t.AddSequence()
	t.AddAction(` p.AddCharacter(buffer[begin:end]) `)
	t.AddSequence()
	t.AddAlternate()
	t.AddExpression()

	/* LEFTARROW       <- '<-' Spacing */
	t.AddRule("LEFTARROW")
	t.AddCharacter(`<`)
	t.AddCharacter(`-`)
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* SLASH           <- '/' Spacing */
	t.AddRule("SLASH")
	t.AddCharacter(`/`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* AND             <- '&' Spacing */
	t.AddRule("AND")
	t.AddCharacter(`&`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* NOT             <- '!' Spacing */
	t.AddRule("NOT")
	t.AddCharacter(`!`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* QUESTION        <- '?' Spacing */
	t.AddRule("QUESTION")
	t.AddCharacter(`?`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* STAR            <- '*' Spacing */
	t.AddRule("STAR")
	t.AddCharacter(`*`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* PLUS            <- '+' Spacing */
	t.AddRule("PLUS")
	t.AddCharacter(`+`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* OPEN            <- '(' Spacing */
	t.AddRule("OPEN")
	t.AddCharacter(`(`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* CLOSE           <- ')' Spacing */
	t.AddRule("CLOSE")
	t.AddCharacter(`)`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* DOT             <- '.' Spacing */
	t.AddRule("DOT")
	t.AddCharacter(`.`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* Spacing         <- (Space / Comment)* */
	t.AddRule("Spacing")
	t.AddName("Space")
	t.AddName("Comment")
	t.AddAlternate()
	t.AddStar()
	t.AddExpression()

	/* Comment         <- '#' (!EndOfLine .)* EndOfLine */
	t.AddRule("Comment")
	t.AddCharacter(`#`)
	t.AddName("EndOfLine")
	t.AddPeekNot()
	t.AddDot()
	t.AddSequence()
	t.AddStar()
	t.AddSequence()
	t.AddName("EndOfLine")
	t.AddSequence()
	t.AddExpression()

	/* Space           <- ' ' / '\t' / EndOfLine */
	t.AddRule("Space")
	t.AddCharacter(` `)
	t.AddCharacter("\t")
	t.AddAlternate()
	t.AddName("EndOfLine")
	t.AddAlternate()
	t.AddExpression()

	/* EndOfLine       <- '\r\n' / '\n' / '\r' */
	t.AddRule("EndOfLine")
	t.AddCharacter("\r")
	t.AddCharacter("\n")
	t.AddSequence()
	t.AddCharacter("\n")
	t.AddAlternate()
	t.AddCharacter("\r")
	t.AddAlternate()
	t.AddExpression()

	/* EndOfFile       <- !. */
	t.AddRule("EndOfFile")
	t.AddDot()
	t.AddPeekNot()
	t.AddExpression()

	/* Action          <- '{' < [^}]* > '}' Spacing */
	t.AddRule("Action")
	t.AddCharacter(`{`)
	t.AddBegin()
	t.AddSequence()
	t.AddCharacter(`}`)
	t.AddPeekNot()
	t.AddDot()
	t.AddSequence()
	t.AddStar()
	t.AddSequence()
	t.AddEnd()
	t.AddSequence()
	t.AddCharacter(`}`)
	t.AddSequence()
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* BEGIN           <- '<' Spacing */
	t.AddRule("BEGIN")
	t.AddCharacter(`<`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	/* END             <- '>' Spacing */
	t.AddRule("END")
	t.AddCharacter(`>`)
	t.AddName("Spacing")
	t.AddSequence()
	t.AddExpression()

	t.Compile("bootstrap.peg.go")
}
