// Code Generated by "build.go buildinfo"  DO NOT EDIT.
package main

const (
	// VERSION is the version of peg
	VERSION   = "unknown"
	// BUILDTIME is the build time of peg
	BUILDTIME = "2024-01-10T10:51:19"
	// COMMIT is the commit hash of peg
	COMMIT    = "047adc6e3cbbd46edaadb58ff9abc399c429ddc0"
	// IS_TAGGED is there a version
	IS_TAGGED = false
)
