// Code Generated by "build.go buildinfo"  DO NOT EDIT.
package main

const (
	// VERSION is the version of peg
	VERSION   = "unknown"
	// BUILDTIME is the build time of peg
	BUILDTIME = "2020-08-26T03:40:14"
	// COMMIT is the commit hash of peg
	COMMIT    = "5cdb3adc061370cdd20392ffe2740cc8db104126"
	// IS_TAGGED is there a version
	IS_TAGGED = false
)
